USE [master]
GO

/****** Object:  Database [dbNgMay]    Script Date: 19/06/2020 9:24:35 CH ******/
CREATE DATABASE [dbNgMay]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbNgMay', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbNgMay.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbNgMay_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbNgMay_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbNgMay].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbNgMay] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbNgMay] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbNgMay] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbNgMay] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbNgMay] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbNgMay] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbNgMay] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbNgMay] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbNgMay] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbNgMay] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbNgMay] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbNgMay] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbNgMay] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbNgMay] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbNgMay] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbNgMay] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbNgMay] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbNgMay] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbNgMay] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbNgMay] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbNgMay] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbNgMay] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbNgMay] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbNgMay] SET  MULTI_USER 
GO

ALTER DATABASE [dbNgMay] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbNgMay] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbNgMay] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbNgMay] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbNgMay] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbNgMay] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbNgMay] SET  READ_WRITE 
GO


