//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTGKNgMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TblCategory
    {
        public int CategoryID { get; set; }
        [Display(Name = "Tên loại")]
        public string CategoryName { get; set; }
        [Display(Name = "Chi tiết loại")]
        public string CategoryNote { get; set; }
    }
}
