//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTGKNgMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblProduct
    {
        public int ProductID { get; set; }
        [Display(Name = "Từ khóa sản phẩm ")]
        public string ProductCode { get; set; }
        [Display(Name = "Tên sản phẩm")]
        public string ProductName { get; set; }
        [Display(Name = "Tên tắt sản phẩm")]
        public string ProductShortName { get; set; }
        [Display(Name = "Chi tiết sản phẩm")]
        public string ProductNote { get; set; }
        [Display(Name = "mã loại sản phẩm")]
        public int CategoryID { get; set; }
        [Display(Name = "Tên Loại sản phẩm")]
        public string CategoryName { get; set; } // thêm ở đây
    }
}
